version: '3.8'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=your_secret_key_here

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chordslegend
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: